CREATE TABLE users (
  userid INTEGER PRIMARY KEY AUTOINCREMENT,
  fullname VARCHAR(40) NOT NULL,
  email VARCHAR(40) NOT NULL,
  password VARCHAR(256) NOT NULL
);

CREATE TABLE saved_items (
  itemid INTEGER PRIMARY KEY AUTOINCREMENT,
  title VARCHAR(256) NOT NULL,
  description VARCHAR(5000) NOT NULL,
  price REAL,
  product_url VARCHAR(2083) NOT NULL,
  image_url VARCHAR(2083) NOT NULL,
  userid INTEGER NOT NULL,
  FOREIGN KEY(userid) REFERENCES users(userid) ON DELETE CASCADE
);

CREATE TABLE search_history (
  image BLOB NOT NULL,
  userid INTEGER NOT NULL,
  searched TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FOREIGN KEY(userid) REFERENCES users(userid) ON DELETE CASCADE
);
